# Configura el puerto en el que el servidor estar치 escuchando
server:
  port: 8111

# Configuraci칩n de la aplicaci칩n Spring
spring:
  # Establece el nombre de la aplicaci칩n
  application:
    name: ms-gateway
  # Configura el uso de Spring Cloud Gateway
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowCredentials: false
            allowedOrigins:
              - "http://localhost:4200"
            allowedHeaders:
              - "Origin"
              - "Access-Control-Allow-Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Origin, Accept"
              - "X-Requested-With"
              - "Access-Control-Request-Method"
              - "Access-Control-Request-Headers"
            exposedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
      routes:
        - id: ms-story
          uri: http://localhost:7777
          predicates:
            - Path=/historias/**
          filters:
            - RewritePath=/historias/(?<path>.*), /$\{path}
        - id: ms-user
          uri: http://localhost:8008
          predicates:
            - Path=/usuarios/**
          filters:
            - RewritePath=/usuarios/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-discovery:8723/eureka/
    enabled: true