version: '2.4'
networks:
    network-database:
        external: true

services:
    ms-gateway:
        image: ms-gateway:0.0.2
        restart: always
        mem_limit: 400m
        ports:
          - "8181:8181"
        environment:
          SERVER_URI: "${SERVER_URI}"
          SPRING_PROFILE: "${SPRING_PROFILE}"
        networks:
            - network-database
    ms-discovery:
        image: ms-discovery:0.0.2
        restart: always
        mem_limit: 400m
        ports:
          - "8723:8723"
        environment:
          SERVER_URI: "${SERVER_URI}"
          SPRING_PROFILE: "${SPRING_PROFILE}"
        networks:
            - network-database
